CMSys/CMSys.Web/Controllers/CourseController.cs
using CMSys.Core.Entities.Catalog;
using CMSys.Core.Repositories;
using CMSys.Web.Models;
using CMSys.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Authorization;

namespace CMSys.Web.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        private readonly IUnitOfWork _uow;
        public CourseController(IUnitOfWork uow) => _uow = uow;
        
        [Route("[controller]/[action]")]
        public IActionResult List(CourseListViewModel model,string courseTypesId, string courseGroupsId, int pageNumber = 1)
        {
            model.CourseTypes = _uow.CourseTypeRepository.List();
            model.CourseGroups = _uow.CourseGroupRepository.List();

            Expression<Func<Course, bool>> filterType = null;
            Expression<Func<Course, bool>> filterGroup = null;

            if (Guid.TryParse(courseTypesId, out var courseTypeId))
            {
                filterType = x => x.CourseTypeId == courseTypeId;
            }
            else if (courseTypesId == "None")
            {
                filterType = x => x.CourseTypeId == null;
            }

            if (Guid.TryParse(courseGroupsId, out var courseGroupId))
            {
                filterGroup = x => x.CourseGroupId == courseGroupId;
            }
            else if (courseGroupsId == "None")
            {
                filterGroup = x => x.CourseGroupId == null;
            }

            model.CourseTypesId = courseTypesId;
            model.CourseGroupsId = courseGroupsId;
            var count = _uow.CourseRepository.Count(filterType, filterGroup);
            model.PaginatedList = PaginatedList<Course>.Create(_uow.CourseRepository.ListCourses(pageNumber, 5, filterType, filterGroup), count, pageNumber, 5);

            return View(model);
        }

        [Route("[controller]/[action]/{id:guid}")]
        public IActionResult Details(Guid id)
        {
            var course = _uow.CourseRepository.Find(id);
            return course == null ? (IActionResult)NotFound() : View(course);
        }
    }
}

CMSys/CMSys.Web/Controllers/TrainerController.cs
using CMSys.Core.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CMSys.Web.Controllers
{
    [Authorize]
    public class TrainerController : Controller
    {
        private readonly IUnitOfWork _uow;

        public TrainerController(IUnitOfWork uow) => _uow = uow;

        [Route("[controller]/[action]")]
        public IActionResult List() => View(_uow.TrainerGroupRepository.List());
    }
}

CMSys/CMSys.Web/Controllers/UserController.cs
using CMSys.Core.Repositories;
using CMSys.Web.Algorithms;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace CMSys.Web.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _uow;

        public UserController(IUnitOfWork uow) => _uow = uow;

        [Route("[controller]/[action]")]
        public IActionResult List(string userId) => View(_uow.UserRepository.Find(Guid.Parse(userId)));

        [HttpGet("[controller]/[action]")]
        public IActionResult EditPassword(string userId)
        {
            return View(_uow.UserRepository.Find(Guid.Parse(userId)));
        }

        [HttpPost("[controller]/[action]")]
        public IActionResult SelfEditPassword(string userId, string oldPass, string firstPass, string secondPass)
        {
            var user = _uow.UserRepository.Find(Guid.Parse(userId));
            if (user == null)
            {
                return NotFound();
            }

            if (firstPass != secondPass)
            {
                Console.WriteLine("o");
                return BadRequest();
            }

            var newPasswordHash = Sha512Hash.ComputeHash(firstPass, user.PasswordSalt);
            if (Sha512Hash.ComputeHash(oldPass, user.PasswordSalt) == newPasswordHash)
            {
                return BadRequest();
            }

            user.PasswordHash = newPasswordHash;

            _uow.Commit();
            return RedirectToAction("List", new { userId });
        }
    }
}

CMSys/CMSys.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CMSys.Web</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/js/site.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CMSys</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="List" asp-route-userId="@User.Claims.First(x=>x.Type=="Id").Value">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Course" asp-action="List">Courses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Trainer" asp-action="List">Trainers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="CourseGroup" asp-action="List">Courses Group</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="TrainerGroup" asp-action="List">Trainers Group</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="List">Users</a>
                            </li>
                        }
                        else if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="List" asp-route-userId="@User.Claims.First(x=>x.Type=="Id").Value">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Trainer" asp-action="List">Trainers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="List">Courses</a>
                            </li>
                        }
                        </ul>
                    </div>
                    <ul class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <span class="navbar-text">
                                    Welcome, @(User.Identity.Name)!
                                </span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Logoff">Log Out</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Login">Log In</a>
                            </li>
                        }
                    </ul>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>