CMSys/CMSys.Web/ViewModels/CourseGroupViewModel.cs
using System.Collections.Generic;
using CMSys.Core.Entities.Catalog;

namespace CMSys.Web.ViewModels
{
    public class CourseGroupViewModel
    {
        public IEnumerable<CourseGroup> CourseGroups { get; set; }
    }
}

CMSys/CMSys.Web/Areas/Admin/Controllers/CourseGroupController.cs
using CMSys.Core.Entities.Catalog;
using CMSys.Core.Repositories;
using CMSys.Web.Areas.Admin.ViewModels;
using CMSys.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CMSys.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CourseGroupController : Controller
    {
        private readonly IUnitOfWork _uow;

        public CourseGroupController(IUnitOfWork uow) => _uow = uow;

        [HttpGet("[area]/[controller]/[action]")]
        public IEnumerable<CourseGroupEditModel> Get() => _uow.CourseGroupRepository.List().Select(Build);

        [Route("[area]/[controller]/[action]")]
        public IActionResult List(CourseGroupViewModel model)
        {
            model.CourseGroups = _uow.CourseGroupRepository.List();

            return View(model);
        }

        [HttpGet("[area]/[controller]/[action]/{id:guid}")]
        public ActionResult<CourseGroupEditModel> Edit(Guid id)
        {
            var courseGroup = _uow.CourseGroupRepository.Find(id);
            if (courseGroup == null)
            {
                return NotFound();
            }

            return Ok(Build(courseGroup));
        }

        [HttpPost("[area]/[controller]/[action]/{id:guid}")]
        public IActionResult Edit(CourseGroupEditModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var courseGroup = _uow.CourseGroupRepository.Find(model.Id);
            if (courseGroup == null)
            {
                return NotFound();
            }

            courseGroup.Name = model.Name;
            courseGroup.VisualOrder = model.VisualOrder;
            courseGroup.Description = string.IsNullOrWhiteSpace(model.Description) ? null : model.Description;

            _uow.Commit();
            return Ok();
        }

        [HttpPost("[area]/[controller]/[action]")]
        public IActionResult Delete(Guid id)
        {
            var courseGroup = _uow.CourseGroupRepository.Find(id);
            if (courseGroup == null)
            {
                return NotFound();
            }

            var groupCoursesCount = _uow.CourseRepository.List().Count(x => x.CourseGroupId == id);

            if (groupCoursesCount != 0)
            {
                return RedirectToAction("List");
            }

            _uow.CourseGroupRepository.Remove(courseGroup);
            _uow.Commit();
            return RedirectToAction("List");
        }

        private static CourseGroupEditModel Build(CourseGroup courseGroup)
        {
            var model = new CourseGroupEditModel
            {
                Id = courseGroup.Id,
                Name = courseGroup.Name,
                VisualOrder = courseGroup.VisualOrder,
                Description = courseGroup.Description,
                
            };

            return model;
        }
    }
}

CMSys/CMSys.Web/Areas/Admin/Views/CourseGroup/List.cshtml
@model CourseGroupViewModel

@{
    ViewBag.Title = "List of Courses Group";
}

<div class="card">
    <div class="card-header">
        <h3>List of courses group</h3>
    </div>
    <div class="card-body">
        <table class="table table-striped table-sm table-bordered">
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Order</th>
                <th>Action</th>
            </tr>
            @foreach (var courseGroup in Model.CourseGroups)
            {
                <tr>
                    <td>@courseGroup.Name</td>
                    <td>@courseGroup.Description</td>
                    <td>@courseGroup.VisualOrder</td>
                    <td>
                        <div class="container">
                            <div class="row float-left">
                                <div class="col">
                                    <button type="button" class="btn btn-link p-0" data-toggle="modal" data-target="#modalEdit" onclick="modalFunctionEditCourseGroup('@courseGroup.Id')">
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                                        </svg>
                                    </button>
                                </div>
                                <div class="col ">
                                    <form asp-controller="CourseGroup" asp-action="Delete" style="display: inline">
                                        <input type="hidden" name="id" value="@courseGroup.Id" />
                                        <button class="btn btn-link p-0"
                                                @if (courseGroup.Courses.Any()) { @Html.Raw("disabled")                 }>
                                            <svg width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd" d="M0 2a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 12.5V5a1 1 0 0 1-1-1V2zm2 3v7.5A1.5 1.5 0 0 0 3.5 14h9a1.5 1.5 0 0 0 1.5-1.5V5H2zm13-3H1v2h14V2zM5 7.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z" />
                                            </svg>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>
<div class="modal" id="modalEdit">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">
                    <span>Edit</span>  <span id="courseGroupLabel"></span>
                </h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body d-flex justify-content-between">
                <form>
                    <input type="hidden" id="courseGroupId" />
                    <div class="form-group">
                        <label>Name</label>
                        <input id="courseGroupName" type="email" class="form-control" aria-describedby="emailHelp" value="0" placeholder="0">
                    </div>
                    <div class="form-group">
                        <label for="courseGroupDescription">Description</label>
                        <textarea id="courseGroupDescription" class="form-control" rows="3"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Visual Order</label>
                        <input id="courseGroupVisualOrder" type="email" class="form-control" aria-describedby="emailHelp" value="0" placeholder="0">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" onclick="modalFunctionUpdateCourseGroup()">Update</button>
            </div>
        </div>
    </div>
</div>